### ISSUE TITLE
Animation state mismatch in 2_Physics scene

### ISSUE THREAD

**Issue by viglucci** [coherence/first-steps-tutorial#1]
In the 2_Physics scene, when a player steals the box from another, the original player with authority remains in the animation as if they are still carrying the box.

https://youtu.be/w3Gq4M6jIyI

**Comment by ccontinisio** [comment]
Thanks Kevin! (sorry for the late reply)

In recent versions of the tutorial, I ended up removing stealing, as it was complicating the tutorial code a lot for what is supposed to be a... first steps tutorial!
So the bug is fixed, I guess :)
